// SPDX-License-Identifier: LGPL-2.1-only OR LGPL-3.0-only OR LicenseRef-KDE-Accepted-LGPL
//
// This file is automatically generated. To regenerate, run `generate_properties.py`.

#include <QtTest>

#include "../SizesProperty.h"

#include "CreateTestInstances.h"

using namespace Union::Properties;
using namespace Qt::StringLiterals;

class TestSizesProperty : public QObject
{
    Q_OBJECT
private Q_SLOTS:
    void testEmpty()
    {
        SizesProperty property;

        // An empty instance should have no values set.
        QVERIFY(!property.width().has_value());
        QVERIFY(!property.height().has_value());
        QVERIFY(!property.spacing().has_value());
        QVERIFY(!property.padding().has_value());
        QVERIFY(!property.margins().has_value());
    }

    void testHasAnyValue()
    {
        SizesProperty property;

        // An empty instance should not have any values.
        QVERIFY(!property.hasAnyValue());

        {
            qreal value;
            property.setWidth(value);
            QVERIFY(property.hasAnyValue());
            property.setWidth(std::nullopt);
            QVERIFY(!property.hasAnyValue());
        }
        {
            qreal value;
            property.setHeight(value);
            QVERIFY(property.hasAnyValue());
            property.setHeight(std::nullopt);
            QVERIFY(!property.hasAnyValue());
        }
        {
            qreal value;
            property.setSpacing(value);
            QVERIFY(property.hasAnyValue());
            property.setSpacing(std::nullopt);
            QVERIFY(!property.hasAnyValue());
        }
        {
            // Assigning an empty property to a value should have no effect.
            property.setPadding(SizeProperty{});
            QVERIFY(!property.hasAnyValue());

            property.setPadding(testSizePropertyInstance());
            QVERIFY(property.hasAnyValue());

            property.setPadding(std::nullopt);
            QVERIFY(!property.hasAnyValue());
        }
        {
            // Assigning an empty property to a value should have no effect.
            property.setMargins(SizeProperty{});
            QVERIFY(!property.hasAnyValue());

            property.setMargins(testSizePropertyInstance());
            QVERIFY(property.hasAnyValue());

            property.setMargins(std::nullopt);
            QVERIFY(!property.hasAnyValue());
        }
    }

    void testResolveProperties()
    {
        SizesProperty source;
        SizesProperty destination;

        QVERIFY(!source.hasAnyValue());
        QVERIFY(!destination.hasAnyValue());

        // Calling resolve on empty source and destination should have no effect.
        SizesProperty::resolveProperties(source, destination);

        QVERIFY(!destination.hasAnyValue());

        source.setWidth(qreal{});
        source.setHeight(qreal{});
        source.setSpacing(qreal{});
        source.setPadding(testSizePropertyInstance());
        source.setMargins(testSizePropertyInstance());

        QVERIFY(source.hasAnyValue());
        QVERIFY(!destination.hasAnyValue());

        SizesProperty::resolveProperties(source, destination);

        QVERIFY(destination.hasAnyValue());

        QCOMPARE(destination.width(), source.width());
        QCOMPARE(destination.height(), source.height());
        QCOMPARE(destination.spacing(), source.spacing());
        QCOMPARE(destination.padding(), source.padding());
        QCOMPARE(destination.margins(), source.margins());
    }
};

QTEST_MAIN(TestSizesProperty)

#include "TestSizesProperty.moc"