// SPDX-License-Identifier: LGPL-2.1-only OR LGPL-3.0-only OR LicenseRef-KDE-Accepted-LGPL
//
// This file is automatically generated. To regenerate, run `generate_properties.py`.

#include <QtTest>

#include "../TextProperty.h"

#include "CreateTestInstances.h"

using namespace Union::Properties;
using namespace Qt::StringLiterals;

class TestTextProperty : public QObject
{
    Q_OBJECT
private Q_SLOTS:
    void testEmpty()
    {
        TextProperty property;

        // An empty instance should have no values set.
        QVERIFY(!property.alignment().has_value());
        QVERIFY(!property.color().has_value());
        QVERIFY(!property.font().has_value());
    }

    void testHasAnyValue()
    {
        TextProperty property;

        // An empty instance should not have any values.
        QVERIFY(!property.hasAnyValue());

        {
            Qt::Alignment value;
            property.setAlignment(value);
            QVERIFY(property.hasAnyValue());
            property.setAlignment(std::nullopt);
            QVERIFY(!property.hasAnyValue());
        }
        {
            QColor value;
            property.setColor(value);
            QVERIFY(property.hasAnyValue());
            property.setColor(std::nullopt);
            QVERIFY(!property.hasAnyValue());
        }
        {
            QFont value;
            property.setFont(value);
            QVERIFY(property.hasAnyValue());
            property.setFont(std::nullopt);
            QVERIFY(!property.hasAnyValue());
        }
    }

    void testResolveProperties()
    {
        TextProperty source;
        TextProperty destination;

        QVERIFY(!source.hasAnyValue());
        QVERIFY(!destination.hasAnyValue());

        // Calling resolve on empty source and destination should have no effect.
        TextProperty::resolveProperties(source, destination);

        QVERIFY(!destination.hasAnyValue());

        source.setAlignment(Qt::Alignment{});
        source.setColor(QColor{});
        source.setFont(QFont{});

        QVERIFY(source.hasAnyValue());
        QVERIFY(!destination.hasAnyValue());

        TextProperty::resolveProperties(source, destination);

        QVERIFY(destination.hasAnyValue());

        QCOMPARE(destination.alignment(), source.alignment());
        QCOMPARE(destination.color(), source.color());
        QCOMPARE(destination.font(), source.font());
    }
};

QTEST_MAIN(TestTextProperty)

#include "TestTextProperty.moc"