// SPDX-License-Identifier: LGPL-2.1-only OR LGPL-3.0-only OR LicenseRef-KDE-Accepted-LGPL
// SPDX-FileCopyrightText: 2024 Arjen Hiemstra <ahiemstra@heimr.nl>
//
// This file is automatically generated from qml_group.h.j2.
// To regenerate, run `tools/propertygenerator/generate_properties.py`.

#pragma once

// clang-format off
#include <QJSValue>
#include <QObject>
#include <QProperty>
#include <qqmlregistration.h>


#include <properties/FontPropertyGroup.h>

// clang-format on

namespace Union
{
namespace Quick
{

class QuickStyle;
/*!
 * \qmltype FontPropertyGroupQuick
 * \inqmlmodule org.kde.union.impl
 * \ingroup qtquick-properties
 *
 * \brief A group object exposing the properties of FontPropertyGroup to QML.
 */
class FontPropertyGroupQuick : public QObject
{
    Q_OBJECT
    QML_ANONYMOUS

public:
    explicit FontPropertyGroupQuick(QuickStyle *style);

    void update(Union::Properties::FontPropertyGroup *newState);
    Q_SIGNAL void updated();

    void refreshColors();

    /*!
     * \qmlproperty QString FontPropertyGroupQuick::family
     *
     * Exposes FontPropertyGroup::family to QML.
     */
    Q_PROPERTY(QJSValue family READ family NOTIFY familyChanged)
    QJSValue family() const;
    Q_SIGNAL void familyChanged();

    /*!
     * \qmlproperty qreal FontPropertyGroupQuick::size
     *
     * Exposes FontPropertyGroup::size to QML.
     */
    Q_PROPERTY(QJSValue size READ size NOTIFY sizeChanged)
    QJSValue size() const;
    Q_SIGNAL void sizeChanged();

    /*!
     * \qmlproperty QFont::Weight FontPropertyGroupQuick::weight
     *
     * Exposes FontPropertyGroup::weight to QML.
     */
    Q_PROPERTY(QJSValue weight READ weight NOTIFY weightChanged)
    QJSValue weight() const;
    Q_SIGNAL void weightChanged();

    /*!
     * \qmlproperty QFont::Style FontPropertyGroupQuick::style
     *
     * Exposes FontPropertyGroup::style to QML.
     */
    Q_PROPERTY(QJSValue style READ style NOTIFY styleChanged)
    QJSValue style() const;
    Q_SIGNAL void styleChanged();

    /*!
     * \qmlproperty int FontPropertyGroupQuick::stretch
     *
     * Exposes FontPropertyGroup::stretch to QML.
     */
    Q_PROPERTY(QJSValue stretch READ stretch NOTIFY stretchChanged)
    QJSValue stretch() const;
    Q_SIGNAL void stretchChanged();

    /*!
     * \qmlproperty QFont::Capitalization FontPropertyGroupQuick::capitalization
     *
     * Exposes FontPropertyGroup::capitalization to QML.
     */
    Q_PROPERTY(QJSValue capitalization READ capitalization NOTIFY capitalizationChanged)
    QJSValue capitalization() const;
    Q_SIGNAL void capitalizationChanged();

    /*!
     * \qmlproperty Union::Properties::TextDecorations FontPropertyGroupQuick::decorations
     *
     * Exposes FontPropertyGroup::decorations to QML.
     */
    Q_PROPERTY(QJSValue decorations READ decorations NOTIFY decorationsChanged)
    QJSValue decorations() const;
    Q_SIGNAL void decorationsChanged();

    /*!
     * \qmlproperty qreal FontPropertyGroupQuick::letterSpacing
     *
     * Exposes FontPropertyGroup::letterSpacing to QML.
     */
    Q_PROPERTY(QJSValue letterSpacing READ letterSpacing NOTIFY letterSpacingChanged)
    QJSValue letterSpacing() const;
    Q_SIGNAL void letterSpacingChanged();

    /*!
     * \qmlproperty qreal FontPropertyGroupQuick::wordSpacing
     *
     * Exposes FontPropertyGroup::wordSpacing to QML.
     */
    Q_PROPERTY(QJSValue wordSpacing READ wordSpacing NOTIFY wordSpacingChanged)
    QJSValue wordSpacing() const;
    Q_SIGNAL void wordSpacingChanged();

    /*! Returns a QFont representing the font. */
    Q_PROPERTY(QFont qFont READ toQFont NOTIFY updated)
    QFont toQFont() const;

private:
    QuickStyle *m_style = nullptr;

    Union::Properties::FontPropertyGroup *m_state = nullptr;
};

}
}