// SPDX-License-Identifier: LGPL-2.1-only OR LGPL-3.0-only OR LicenseRef-KDE-Accepted-LGPL
//
// This file is automatically generated. To regenerate, run `tools/propertygenerator/generate_properties.py`.

#pragma once

// clang-format off
#include <QObject>
#include <QProperty>
#include <qqmlregistration.h>


#include <properties/IconProperty.h>

#include "AlignmentPropertyGroup.h"
// clang-format on

class IconPropertyGroup : public QObject
{
    Q_OBJECT
    QML_ANONYMOUS

public:
    IconPropertyGroup();

    void update(const Union::Properties::IconProperty &newState);
    Q_SIGNAL void updated();

    Q_PROPERTY(AlignmentPropertyGroup *alignment READ alignment CONSTANT)
    AlignmentPropertyGroup *alignment() const;

    Q_PROPERTY(qreal width READ width NOTIFY widthChanged)
    qreal width() const;
    Q_SIGNAL void widthChanged();

    Q_PROPERTY(qreal height READ height NOTIFY heightChanged)
    qreal height() const;
    Q_SIGNAL void heightChanged();

    Q_PROPERTY(QString name READ name NOTIFY nameChanged)
    QString name() const;
    Q_SIGNAL void nameChanged();

    Q_PROPERTY(QUrl source READ source NOTIFY sourceChanged)
    QUrl source() const;
    Q_SIGNAL void sourceChanged();

private:
    std::unique_ptr<AlignmentPropertyGroup> m_alignment;
    Union::Properties::IconProperty m_state;
};