// SPDX-License-Identifier: LGPL-2.1-only OR LGPL-3.0-only OR LicenseRef-KDE-Accepted-LGPL
//
// This file is automatically generated. To regenerate, run `tools/propertygenerator/generate_properties.py`.

#include "IconPropertyGroup.h"

using namespace Union::Properties;
using namespace Qt::StringLiterals;

IconPropertyGroup::IconPropertyGroup()
{
    m_alignment = std::make_unique<AlignmentPropertyGroup>();
}

void IconPropertyGroup::update(const IconProperty &newState)
{
    m_state = newState;
    m_alignment->update(newState.alignment().value_or(AlignmentProperty{}));
    Q_EMIT widthChanged();
    Q_EMIT heightChanged();
    Q_EMIT nameChanged();
    Q_EMIT sourceChanged();

    Q_EMIT updated();
}

AlignmentPropertyGroup *IconPropertyGroup::alignment() const
{
    return m_alignment.get();
}

qreal IconPropertyGroup::width() const
{
    return m_state.width().value_or(qreal{});
}

qreal IconPropertyGroup::height() const
{
    return m_state.height().value_or(qreal{});
}

QString IconPropertyGroup::name() const
{
    return m_state.name().value_or(QString{});
}

QUrl IconPropertyGroup::source() const
{
    return m_state.source().value_or(QUrl{});
}

#include "moc_IconPropertyGroup.cpp"