// SPDX-License-Identifier: LGPL-2.1-only OR LGPL-3.0-only OR LicenseRef-KDE-Accepted-LGPL
//
// This file is automatically generated. To regenerate, run `tools/propertygenerator/generate_properties.py`.

#include "ImagePropertyGroup.h"

using namespace Union::Properties;
using namespace Qt::StringLiterals;

ImagePropertyGroup::ImagePropertyGroup()
{
}

void ImagePropertyGroup::update(const ImageProperty &newState)
{
    m_state = newState;
    Q_EMIT imageDataChanged();
    Q_EMIT widthChanged();
    Q_EMIT heightChanged();
    Q_EMIT xOffsetChanged();
    Q_EMIT yOffsetChanged();
    Q_EMIT flagsChanged();

    Q_EMIT updated();
}

QImage ImagePropertyGroup::imageData() const
{
    return m_state.imageData().value_or(QImage{});
}

qreal ImagePropertyGroup::width() const
{
    return m_state.width().value_or(qreal{});
}

qreal ImagePropertyGroup::height() const
{
    return m_state.height().value_or(qreal{});
}

qreal ImagePropertyGroup::xOffset() const
{
    return m_state.xOffset().value_or(qreal{});
}

qreal ImagePropertyGroup::yOffset() const
{
    return m_state.yOffset().value_or(qreal{});
}

Union::Properties::ImageFlags ImagePropertyGroup::flags() const
{
    return m_state.flags().value_or(Union::Properties::ImageFlags{});
}

#include "moc_ImagePropertyGroup.cpp"