// SPDX-License-Identifier: LGPL-2.1-only OR LGPL-3.0-only OR LicenseRef-KDE-Accepted-LGPL
// SPDX-FileCopyrightText: 2024 Arjen Hiemstra <ahiemstra@heimr.nl>
//
// This file is automatically generated from qml_group.h.j2.
// To regenerate, run `tools/propertygenerator/generate_properties.py`.

#pragma once

// clang-format off
#include <QJSValue>
#include <QObject>
#include <QProperty>
#include <qqmlregistration.h>


#include <properties/OffsetPropertyGroup.h>

// clang-format on

namespace Union
{
namespace Quick
{

class QuickStyle;
/*!
 * \qmltype OffsetPropertyGroupQuick
 * \inqmlmodule org.kde.union.impl
 * \ingroup qtquick-properties
 *
 * \brief A group object exposing the properties of OffsetPropertyGroup to QML.
 */
class OffsetPropertyGroupQuick : public QObject
{
    Q_OBJECT
    QML_ANONYMOUS

public:
    explicit OffsetPropertyGroupQuick(QuickStyle *style);

    void update(Union::Properties::OffsetPropertyGroup *newState);
    Q_SIGNAL void updated();

    void refreshColors();

    /*!
     * \qmlproperty qreal OffsetPropertyGroupQuick::horizontal
     *
     * Exposes OffsetPropertyGroup::horizontal to QML.
     */
    Q_PROPERTY(QJSValue horizontal READ horizontal NOTIFY horizontalChanged)
    QJSValue horizontal() const;
    Q_SIGNAL void horizontalChanged();

    /*!
     * \qmlproperty qreal OffsetPropertyGroupQuick::vertical
     *
     * Exposes OffsetPropertyGroup::vertical to QML.
     */
    Q_PROPERTY(QJSValue vertical READ vertical NOTIFY verticalChanged)
    QJSValue vertical() const;
    Q_SIGNAL void verticalChanged();

private:
    QuickStyle *m_style = nullptr;

    Union::Properties::OffsetPropertyGroup *m_state = nullptr;
};

}
}