// SPDX-License-Identifier: LGPL-2.1-only OR LGPL-3.0-only OR LicenseRef-KDE-Accepted-LGPL
//
// This file is automatically generated. To regenerate, run `tools/propertygenerator/generate_properties.py`.

#include "PalettePropertyGroup.h"

#include <QQmlEngine>

#include "QuickStyle.h"

using namespace Union::Properties;
using namespace Qt::StringLiterals;

PalettePropertyGroup::PalettePropertyGroup(QuickStyle *style)
    : QObject()
    , m_style(style)
{
}

void PalettePropertyGroup::update(const PaletteProperty &newState)
{
    m_state = newState;
    Q_EMIT accentChanged();
    Q_EMIT alternateBaseChanged();
    Q_EMIT baseChanged();
    Q_EMIT brightTextChanged();
    Q_EMIT buttonChanged();
    Q_EMIT buttonTextChanged();
    Q_EMIT darkChanged();
    Q_EMIT highlightChanged();
    Q_EMIT highlightedTextChanged();
    Q_EMIT lightChanged();
    Q_EMIT linkChanged();
    Q_EMIT linkVisitedChanged();
    Q_EMIT midChanged();
    Q_EMIT midlightChanged();
    Q_EMIT placeholderTextChanged();
    Q_EMIT shadowChanged();
    Q_EMIT textChanged();
    Q_EMIT toolTipBaseChanged();
    Q_EMIT toolTipTextChanged();
    Q_EMIT windowChanged();
    Q_EMIT windowTextChanged();
    Q_EMIT positiveChanged();
    Q_EMIT neutralChanged();
    Q_EMIT negativeChanged();

    if (!m_component) {
        // We need a QML engine to create a QQmlComponent. Try to determine it
        // based on the style we're part of.
        Q_ASSERT(m_style);
        m_component = new QQmlComponent(m_style->engine());
        m_component->setData("import QtQuick; Palette { }"_ba, QUrl{});
    }

    if (m_palette) {
        delete m_palette;
    }

    m_palette = m_component->create();

    if (m_state.accent()) {
        m_palette->setProperty("accent", QVariant::fromValue(m_state.accent().value()));
    }

    if (m_state.alternateBase()) {
        m_palette->setProperty("alternateBase", QVariant::fromValue(m_state.alternateBase().value()));
    }

    if (m_state.base()) {
        m_palette->setProperty("base", QVariant::fromValue(m_state.base().value()));
    }

    if (m_state.brightText()) {
        m_palette->setProperty("brightText", QVariant::fromValue(m_state.brightText().value()));
    }

    if (m_state.button()) {
        m_palette->setProperty("button", QVariant::fromValue(m_state.button().value()));
    }

    if (m_state.buttonText()) {
        m_palette->setProperty("buttonText", QVariant::fromValue(m_state.buttonText().value()));
    }

    if (m_state.dark()) {
        m_palette->setProperty("dark", QVariant::fromValue(m_state.dark().value()));
    }

    if (m_state.highlight()) {
        m_palette->setProperty("highlight", QVariant::fromValue(m_state.highlight().value()));
    }

    if (m_state.highlightedText()) {
        m_palette->setProperty("highlightedText", QVariant::fromValue(m_state.highlightedText().value()));
    }

    if (m_state.light()) {
        m_palette->setProperty("light", QVariant::fromValue(m_state.light().value()));
    }

    if (m_state.link()) {
        m_palette->setProperty("link", QVariant::fromValue(m_state.link().value()));
    }

    if (m_state.linkVisited()) {
        m_palette->setProperty("linkVisited", QVariant::fromValue(m_state.linkVisited().value()));
    }

    if (m_state.mid()) {
        m_palette->setProperty("mid", QVariant::fromValue(m_state.mid().value()));
    }

    if (m_state.midlight()) {
        m_palette->setProperty("midlight", QVariant::fromValue(m_state.midlight().value()));
    }

    if (m_state.placeholderText()) {
        m_palette->setProperty("placeholderText", QVariant::fromValue(m_state.placeholderText().value()));
    }

    if (m_state.shadow()) {
        m_palette->setProperty("shadow", QVariant::fromValue(m_state.shadow().value()));
    }

    if (m_state.text()) {
        m_palette->setProperty("text", QVariant::fromValue(m_state.text().value()));
    }

    if (m_state.toolTipBase()) {
        m_palette->setProperty("toolTipBase", QVariant::fromValue(m_state.toolTipBase().value()));
    }

    if (m_state.toolTipText()) {
        m_palette->setProperty("toolTipText", QVariant::fromValue(m_state.toolTipText().value()));
    }

    if (m_state.window()) {
        m_palette->setProperty("window", QVariant::fromValue(m_state.window().value()));
    }

    if (m_state.windowText()) {
        m_palette->setProperty("windowText", QVariant::fromValue(m_state.windowText().value()));
    }

    Q_EMIT updated();
}

QJSValue PalettePropertyGroup::accent() const
{
    auto value = m_state.accent();
    if (value) {
        return m_style->engine()->toScriptValue(value.value());
    }

    return QJSValue(QJSValue::UndefinedValue);
}

QJSValue PalettePropertyGroup::alternateBase() const
{
    auto value = m_state.alternateBase();
    if (value) {
        return m_style->engine()->toScriptValue(value.value());
    }

    return QJSValue(QJSValue::UndefinedValue);
}

QJSValue PalettePropertyGroup::base() const
{
    auto value = m_state.base();
    if (value) {
        return m_style->engine()->toScriptValue(value.value());
    }

    return QJSValue(QJSValue::UndefinedValue);
}

QJSValue PalettePropertyGroup::brightText() const
{
    auto value = m_state.brightText();
    if (value) {
        return m_style->engine()->toScriptValue(value.value());
    }

    return QJSValue(QJSValue::UndefinedValue);
}

QJSValue PalettePropertyGroup::button() const
{
    auto value = m_state.button();
    if (value) {
        return m_style->engine()->toScriptValue(value.value());
    }

    return QJSValue(QJSValue::UndefinedValue);
}

QJSValue PalettePropertyGroup::buttonText() const
{
    auto value = m_state.buttonText();
    if (value) {
        return m_style->engine()->toScriptValue(value.value());
    }

    return QJSValue(QJSValue::UndefinedValue);
}

QJSValue PalettePropertyGroup::dark() const
{
    auto value = m_state.dark();
    if (value) {
        return m_style->engine()->toScriptValue(value.value());
    }

    return QJSValue(QJSValue::UndefinedValue);
}

QJSValue PalettePropertyGroup::highlight() const
{
    auto value = m_state.highlight();
    if (value) {
        return m_style->engine()->toScriptValue(value.value());
    }

    return QJSValue(QJSValue::UndefinedValue);
}

QJSValue PalettePropertyGroup::highlightedText() const
{
    auto value = m_state.highlightedText();
    if (value) {
        return m_style->engine()->toScriptValue(value.value());
    }

    return QJSValue(QJSValue::UndefinedValue);
}

QJSValue PalettePropertyGroup::light() const
{
    auto value = m_state.light();
    if (value) {
        return m_style->engine()->toScriptValue(value.value());
    }

    return QJSValue(QJSValue::UndefinedValue);
}

QJSValue PalettePropertyGroup::link() const
{
    auto value = m_state.link();
    if (value) {
        return m_style->engine()->toScriptValue(value.value());
    }

    return QJSValue(QJSValue::UndefinedValue);
}

QJSValue PalettePropertyGroup::linkVisited() const
{
    auto value = m_state.linkVisited();
    if (value) {
        return m_style->engine()->toScriptValue(value.value());
    }

    return QJSValue(QJSValue::UndefinedValue);
}

QJSValue PalettePropertyGroup::mid() const
{
    auto value = m_state.mid();
    if (value) {
        return m_style->engine()->toScriptValue(value.value());
    }

    return QJSValue(QJSValue::UndefinedValue);
}

QJSValue PalettePropertyGroup::midlight() const
{
    auto value = m_state.midlight();
    if (value) {
        return m_style->engine()->toScriptValue(value.value());
    }

    return QJSValue(QJSValue::UndefinedValue);
}

QJSValue PalettePropertyGroup::placeholderText() const
{
    auto value = m_state.placeholderText();
    if (value) {
        return m_style->engine()->toScriptValue(value.value());
    }

    return QJSValue(QJSValue::UndefinedValue);
}

QJSValue PalettePropertyGroup::shadow() const
{
    auto value = m_state.shadow();
    if (value) {
        return m_style->engine()->toScriptValue(value.value());
    }

    return QJSValue(QJSValue::UndefinedValue);
}

QJSValue PalettePropertyGroup::text() const
{
    auto value = m_state.text();
    if (value) {
        return m_style->engine()->toScriptValue(value.value());
    }

    return QJSValue(QJSValue::UndefinedValue);
}

QJSValue PalettePropertyGroup::toolTipBase() const
{
    auto value = m_state.toolTipBase();
    if (value) {
        return m_style->engine()->toScriptValue(value.value());
    }

    return QJSValue(QJSValue::UndefinedValue);
}

QJSValue PalettePropertyGroup::toolTipText() const
{
    auto value = m_state.toolTipText();
    if (value) {
        return m_style->engine()->toScriptValue(value.value());
    }

    return QJSValue(QJSValue::UndefinedValue);
}

QJSValue PalettePropertyGroup::window() const
{
    auto value = m_state.window();
    if (value) {
        return m_style->engine()->toScriptValue(value.value());
    }

    return QJSValue(QJSValue::UndefinedValue);
}

QJSValue PalettePropertyGroup::windowText() const
{
    auto value = m_state.windowText();
    if (value) {
        return m_style->engine()->toScriptValue(value.value());
    }

    return QJSValue(QJSValue::UndefinedValue);
}

QJSValue PalettePropertyGroup::positive() const
{
    auto value = m_state.positive();
    if (value) {
        return m_style->engine()->toScriptValue(value.value());
    }

    return QJSValue(QJSValue::UndefinedValue);
}

QJSValue PalettePropertyGroup::neutral() const
{
    auto value = m_state.neutral();
    if (value) {
        return m_style->engine()->toScriptValue(value.value());
    }

    return QJSValue(QJSValue::UndefinedValue);
}

QJSValue PalettePropertyGroup::negative() const
{
    auto value = m_state.negative();
    if (value) {
        return m_style->engine()->toScriptValue(value.value());
    }

    return QJSValue(QJSValue::UndefinedValue);
}

QObject *PalettePropertyGroup::quickPalette() const
{
    return m_palette;
}

#include "moc_PalettePropertyGroup.cpp"
