// SPDX-License-Identifier: LGPL-2.1-only OR LGPL-3.0-only OR LicenseRef-KDE-Accepted-LGPL
//
// This file is automatically generated. To regenerate, run `tools/propertygenerator/generate_properties.py`.

#include "PalettePropertyGroup.h"

using namespace Union::Properties;
using namespace Qt::StringLiterals;

PalettePropertyGroup::PalettePropertyGroup()
{
}

void PalettePropertyGroup::update(const PaletteProperty &newState)
{
    m_state = newState;
    Q_EMIT accentChanged();
    Q_EMIT alternateBaseChanged();
    Q_EMIT baseChanged();
    Q_EMIT brightTextChanged();
    Q_EMIT buttonChanged();
    Q_EMIT buttonTextChanged();
    Q_EMIT darkChanged();
    Q_EMIT highlightChanged();
    Q_EMIT highlightedTextChanged();
    Q_EMIT lightChanged();
    Q_EMIT linkChanged();
    Q_EMIT linkVisitedChanged();
    Q_EMIT midChanged();
    Q_EMIT midlightChanged();
    Q_EMIT placeholderTextChanged();
    Q_EMIT shadowChanged();
    Q_EMIT textChanged();
    Q_EMIT toolTipBaseChanged();
    Q_EMIT toolTipTextChanged();
    Q_EMIT windowChanged();
    Q_EMIT windowTextChanged();
    Q_EMIT positiveChanged();
    Q_EMIT neutralChanged();
    Q_EMIT negativeChanged();

    if (!m_component) {
        // Dirty hack to get at the main QML engine.
        m_component = new QQmlComponent(qmlEngine(qGuiApp->allWindows().first()));
        m_component->setData("import QtQuick; Palette { }"_ba, QUrl{});
    }

    if (m_palette) {
        delete m_palette;
    }

    m_palette = m_component->create();

    if (m_state.accent()) {
        m_palette->setProperty("accent", QVariant::fromValue(m_state.accent().value()));
    }

    if (m_state.alternateBase()) {
        m_palette->setProperty("alternateBase", QVariant::fromValue(m_state.alternateBase().value()));
    }

    if (m_state.base()) {
        m_palette->setProperty("base", QVariant::fromValue(m_state.base().value()));
    }

    if (m_state.brightText()) {
        m_palette->setProperty("brightText", QVariant::fromValue(m_state.brightText().value()));
    }

    if (m_state.button()) {
        m_palette->setProperty("button", QVariant::fromValue(m_state.button().value()));
    }

    if (m_state.buttonText()) {
        m_palette->setProperty("buttonText", QVariant::fromValue(m_state.buttonText().value()));
    }

    if (m_state.dark()) {
        m_palette->setProperty("dark", QVariant::fromValue(m_state.dark().value()));
    }

    if (m_state.highlight()) {
        m_palette->setProperty("highlight", QVariant::fromValue(m_state.highlight().value()));
    }

    if (m_state.highlightedText()) {
        m_palette->setProperty("highlightedText", QVariant::fromValue(m_state.highlightedText().value()));
    }

    if (m_state.light()) {
        m_palette->setProperty("light", QVariant::fromValue(m_state.light().value()));
    }

    if (m_state.link()) {
        m_palette->setProperty("link", QVariant::fromValue(m_state.link().value()));
    }

    if (m_state.linkVisited()) {
        m_palette->setProperty("linkVisited", QVariant::fromValue(m_state.linkVisited().value()));
    }

    if (m_state.mid()) {
        m_palette->setProperty("mid", QVariant::fromValue(m_state.mid().value()));
    }

    if (m_state.midlight()) {
        m_palette->setProperty("midlight", QVariant::fromValue(m_state.midlight().value()));
    }

    if (m_state.placeholderText()) {
        m_palette->setProperty("placeholderText", QVariant::fromValue(m_state.placeholderText().value()));
    }

    if (m_state.shadow()) {
        m_palette->setProperty("shadow", QVariant::fromValue(m_state.shadow().value()));
    }

    if (m_state.text()) {
        m_palette->setProperty("text", QVariant::fromValue(m_state.text().value()));
    }

    if (m_state.toolTipBase()) {
        m_palette->setProperty("toolTipBase", QVariant::fromValue(m_state.toolTipBase().value()));
    }

    if (m_state.toolTipText()) {
        m_palette->setProperty("toolTipText", QVariant::fromValue(m_state.toolTipText().value()));
    }

    if (m_state.window()) {
        m_palette->setProperty("window", QVariant::fromValue(m_state.window().value()));
    }

    if (m_state.windowText()) {
        m_palette->setProperty("windowText", QVariant::fromValue(m_state.windowText().value()));
    }

    Q_EMIT updated();
}

QColor PalettePropertyGroup::accent() const
{
    return m_state.accent().value_or(QColor{});
}

QColor PalettePropertyGroup::alternateBase() const
{
    return m_state.alternateBase().value_or(QColor{});
}

QColor PalettePropertyGroup::base() const
{
    return m_state.base().value_or(QColor{});
}

QColor PalettePropertyGroup::brightText() const
{
    return m_state.brightText().value_or(QColor{});
}

QColor PalettePropertyGroup::button() const
{
    return m_state.button().value_or(QColor{});
}

QColor PalettePropertyGroup::buttonText() const
{
    return m_state.buttonText().value_or(QColor{});
}

QColor PalettePropertyGroup::dark() const
{
    return m_state.dark().value_or(QColor{});
}

QColor PalettePropertyGroup::highlight() const
{
    return m_state.highlight().value_or(QColor{});
}

QColor PalettePropertyGroup::highlightedText() const
{
    return m_state.highlightedText().value_or(QColor{});
}

QColor PalettePropertyGroup::light() const
{
    return m_state.light().value_or(QColor{});
}

QColor PalettePropertyGroup::link() const
{
    return m_state.link().value_or(QColor{});
}

QColor PalettePropertyGroup::linkVisited() const
{
    return m_state.linkVisited().value_or(QColor{});
}

QColor PalettePropertyGroup::mid() const
{
    return m_state.mid().value_or(QColor{});
}

QColor PalettePropertyGroup::midlight() const
{
    return m_state.midlight().value_or(QColor{});
}

QColor PalettePropertyGroup::placeholderText() const
{
    return m_state.placeholderText().value_or(QColor{});
}

QColor PalettePropertyGroup::shadow() const
{
    return m_state.shadow().value_or(QColor{});
}

QColor PalettePropertyGroup::text() const
{
    return m_state.text().value_or(QColor{});
}

QColor PalettePropertyGroup::toolTipBase() const
{
    return m_state.toolTipBase().value_or(QColor{});
}

QColor PalettePropertyGroup::toolTipText() const
{
    return m_state.toolTipText().value_or(QColor{});
}

QColor PalettePropertyGroup::window() const
{
    return m_state.window().value_or(QColor{});
}

QColor PalettePropertyGroup::windowText() const
{
    return m_state.windowText().value_or(QColor{});
}

QColor PalettePropertyGroup::positive() const
{
    return m_state.positive().value_or(QColor{});
}

QColor PalettePropertyGroup::neutral() const
{
    return m_state.neutral().value_or(QColor{});
}

QColor PalettePropertyGroup::negative() const
{
    return m_state.negative().value_or(QColor{});
}

QObject *PalettePropertyGroup::quickPalette() const
{
    return m_palette;
}

#include "moc_PalettePropertyGroup.cpp"