// SPDX-License-Identifier: LGPL-2.1-only OR LGPL-3.0-only OR LicenseRef-KDE-Accepted-LGPL
// SPDX-FileCopyrightText: 2024 Arjen Hiemstra <ahiemstra@heimr.nl>
//
// This file is automatically generated from qml_group.cpp.j2.
// To regenerate, run `tools/propertygenerator/generate_properties.py`.

#include "ShadowPropertyGroupQuick.h"

#include <QQmlEngine>

#include "QuickStyle.h"

using namespace Union::Properties;
using namespace Union::Quick;
using namespace Qt::StringLiterals;

ShadowPropertyGroupQuick::ShadowPropertyGroupQuick(QuickStyle *style)
    : QObject()
    , m_style(style)
{
    m_offset = std::make_unique<OffsetPropertyGroupQuick>(m_style);
}

void ShadowPropertyGroupQuick::update(ShadowPropertyGroup *newState)
{
    if (newState == m_state) {
        return;
    }

    m_state = newState;

    if (!newState) {
        m_offset->update(nullptr);
    } else {
        m_offset->update(newState->offset());
    }

    Q_EMIT colorChanged();
    Q_EMIT sizeChanged();
    Q_EMIT blurChanged();
    Q_EMIT updated();
}

void ShadowPropertyGroupQuick::refreshColors()
{
    m_offset->refreshColors();
    Q_EMIT colorChanged();
}

OffsetPropertyGroupQuick *ShadowPropertyGroupQuick::offset() const
{
    return m_offset.get();
}

QJSValue ShadowPropertyGroupQuick::color() const
{
    if (!m_state) {
        return QJSValue(QJSValue::UndefinedValue);
    }

    auto value = m_state->color();
    if (value) {
        return m_style->engine()->toScriptValue(value.value().toQColor());
    }

    return QJSValue(QJSValue::UndefinedValue);
}

QJSValue ShadowPropertyGroupQuick::size() const
{
    if (!m_state) {
        return QJSValue(QJSValue::UndefinedValue);
    }

    auto value = m_state->size();
    if (value) {
        return m_style->engine()->toScriptValue(value.value());
    }

    return QJSValue(QJSValue::UndefinedValue);
}

QJSValue ShadowPropertyGroupQuick::blur() const
{
    if (!m_state) {
        return QJSValue(QJSValue::UndefinedValue);
    }

    auto value = m_state->blur();
    if (value) {
        return m_style->engine()->toScriptValue(value.value());
    }

    return QJSValue(QJSValue::UndefinedValue);
}

#include "moc_ShadowPropertyGroupQuick.cpp"