// SPDX-License-Identifier: LGPL-2.1-only OR LGPL-3.0-only OR LicenseRef-KDE-Accepted-LGPL
// SPDX-FileCopyrightText: 2024 Arjen Hiemstra <ahiemstra@heimr.nl>
//
// This file is automatically generated from qml_group.cpp.j2.
// To regenerate, run `tools/propertygenerator/generate_properties.py`.

#include "TextPropertyGroupQuick.h"

#include <QQmlEngine>

#include "QuickStyle.h"

using namespace Union::Properties;
using namespace Union::Quick;
using namespace Qt::StringLiterals;

TextPropertyGroupQuick::TextPropertyGroupQuick(QuickStyle *style)
    : QObject()
    , m_style(style)
{
    m_alignment = std::make_unique<AlignmentPropertyGroupQuick>(m_style);
    m_font = std::make_unique<FontPropertyGroupQuick>(m_style);
}

void TextPropertyGroupQuick::update(TextPropertyGroup *newState)
{
    if (newState == m_state) {
        return;
    }

    m_state = newState;

    if (!newState) {
        m_alignment->update(nullptr);
        m_font->update(nullptr);
    } else {
        m_alignment->update(newState->alignment());
        m_font->update(newState->font());
    }

    Q_EMIT colorChanged();
    Q_EMIT wrapModeChanged();
    Q_EMIT elideChanged();
    Q_EMIT updated();
}

void TextPropertyGroupQuick::refreshColors()
{
    m_alignment->refreshColors();
    m_font->refreshColors();
    Q_EMIT colorChanged();
}

AlignmentPropertyGroupQuick *TextPropertyGroupQuick::alignment() const
{
    return m_alignment.get();
}

FontPropertyGroupQuick *TextPropertyGroupQuick::font() const
{
    return m_font.get();
}

QJSValue TextPropertyGroupQuick::color() const
{
    if (!m_state) {
        return QJSValue(QJSValue::UndefinedValue);
    }

    auto value = m_state->color();
    if (value) {
        return m_style->engine()->toScriptValue(value.value().toQColor());
    }

    return QJSValue(QJSValue::UndefinedValue);
}

QJSValue TextPropertyGroupQuick::wrapMode() const
{
    if (!m_state) {
        return QJSValue(QJSValue::UndefinedValue);
    }

    auto value = m_state->wrapMode();
    if (value) {
        return m_style->engine()->toScriptValue(value.value());
    }

    return QJSValue(QJSValue::UndefinedValue);
}

QJSValue TextPropertyGroupQuick::elide() const
{
    if (!m_state) {
        return QJSValue(QJSValue::UndefinedValue);
    }

    auto value = m_state->elide();
    if (value) {
        return m_style->engine()->toScriptValue(value.value());
    }

    return QJSValue(QJSValue::UndefinedValue);
}

#include "moc_TextPropertyGroupQuick.cpp"