// SPDX-License-Identifier: LGPL-2.1-only OR LGPL-3.0-only OR LicenseRef-KDE-Accepted-LGPL
//
// This file is automatically generated. To regenerate, run `tools/propertygenerator/generate_properties.py`.

#pragma once

// clang-format off
#include <QObject>
#include <QProperty>
#include <qqmlregistration.h>

#include <QColor>
#include <QFont>

#include <properties/TextProperty.h>

#include "AlignmentPropertyGroup.h"
// clang-format on

class TextPropertyGroup : public QObject
{
    Q_OBJECT
    QML_ANONYMOUS

public:
    TextPropertyGroup();

    void update(const Union::Properties::TextProperty &newState);

    Q_PROPERTY(AlignmentPropertyGroup *alignment READ alignment CONSTANT)
    AlignmentPropertyGroup *alignment() const;

    Q_PROPERTY(QColor color READ color WRITE setColor BINDABLE bindableColor NOTIFY colorChanged)
    QColor color() const;
    void setColor(const QColor &newValue);
    QBindable<QColor> bindableColor();
    Q_SIGNAL void colorChanged();

    Q_PROPERTY(QFont font READ font WRITE setFont BINDABLE bindableFont NOTIFY fontChanged)
    QFont font() const;
    void setFont(const QFont &newValue);
    QBindable<QFont> bindableFont();
    Q_SIGNAL void fontChanged();

private:
    std::unique_ptr<AlignmentPropertyGroup> m_alignment;
    Q_OBJECT_BINDABLE_PROPERTY(TextPropertyGroup, QColor, m_color, &TextPropertyGroup::colorChanged)
    Q_OBJECT_BINDABLE_PROPERTY(TextPropertyGroup, QFont, m_font, &TextPropertyGroup::fontChanged)
};