// SPDX-License-Identifier: LGPL-2.1-only OR LGPL-3.0-only OR LicenseRef-KDE-Accepted-LGPL
// SPDX-FileCopyrightText: 2024 Arjen Hiemstra <ahiemstra@heimr.nl>
//
// This file is automatically generated from autotest.cpp.j2.
// To regenerate, run `tools/propertygenerator/generate_properties.py`.

#include <QtTest>

#include <properties/LinePropertyGroup.h>

#include "CreateTestInstances.h"

using namespace Union::Properties;
using namespace Qt::StringLiterals;

class TestLinePropertyGroup : public QObject
{
    Q_OBJECT
private Q_SLOTS:
    void testNull()
    {
        auto property = std::make_unique<LinePropertyGroup>();

        // A null instance should not have any values for its properties.
        QVERIFY(!property->size().has_value());
        QVERIFY(!property->color().has_value());
        QVERIFY(!property->style().has_value());
    }

    void testEmpty()
    {
        auto property = LinePropertyGroup::empty();

        // An empty instance should only have values that are considered "empty".
        QCOMPARE(property->size().value(), emptyValue<qreal>());
        QCOMPARE(property->color().value(), emptyValue<Union::Color>());
        QCOMPARE(property->style().value(), emptyValue<Union::Properties::LineStyle>());
    }

    void testHasAnyValue()
    {
        auto property = std::make_unique<LinePropertyGroup>();

        // An empty instance should not have any values for its properties.
        QVERIFY(!property->hasAnyValue());

        {
            qreal value;
            property->setSize(value);
            QVERIFY(property->hasAnyValue());
            property->setSize(std::nullopt);
            QVERIFY(!property->hasAnyValue());
        }
        {
            Union::Color value;
            property->setColor(value);
            QVERIFY(property->hasAnyValue());
            property->setColor(std::nullopt);
            QVERIFY(!property->hasAnyValue());
        }
        {
            Union::Properties::LineStyle value;
            property->setStyle(value);
            QVERIFY(property->hasAnyValue());
            property->setStyle(std::nullopt);
            QVERIFY(!property->hasAnyValue());
        }
    }

    void testResolveProperties()
    {
        auto source = std::make_unique<LinePropertyGroup>();
        auto destination = std::make_unique<LinePropertyGroup>();

        QVERIFY(!source->hasAnyValue());
        QVERIFY(!destination->hasAnyValue());

        // Calling resolve on empty source and destination should have no effect.
        LinePropertyGroup::resolveProperties(source.get(), destination.get());

        QVERIFY(!destination->hasAnyValue());

        source->setSize(qreal{});
        source->setColor(Union::Color{});
        source->setStyle(Union::Properties::LineStyle{});

        QVERIFY(source->hasAnyValue());
        QVERIFY(!destination->hasAnyValue());

        LinePropertyGroup::resolveProperties(source.get(), destination.get());

        QVERIFY(destination->hasAnyValue());

        QCOMPARE(destination->size(), source->size());
        QCOMPARE(destination->color(), source->color());
        QCOMPARE(destination->style(), source->style());
    }

    void testDataStream()
    {
        auto group = testLinePropertyGroupInstance();

        QByteArray data;
        QDataStream writeStream(&data, QIODevice::WriteOnly);
        writeStream << group.get();

        QCOMPARE(writeStream.status(), QDataStream::Status::Ok);
        QVERIFY(data.size() > 0);

        QDataStream readStream(data);
        auto readGroup = std::make_unique<LinePropertyGroup>();
        readStream >> readGroup;

        QCOMPARE(readStream.status(), QDataStream::Status::Ok);
        QCOMPARE(*readGroup, *group);
    }
};

QTEST_MAIN(TestLinePropertyGroup)

#include "TestLinePropertyGroup.moc"