// SPDX-License-Identifier: LGPL-2.1-only OR LGPL-3.0-only OR LicenseRef-KDE-Accepted-LGPL
// SPDX-FileCopyrightText: 2024 Arjen Hiemstra <ahiemstra@heimr.nl>
//
// This file is automatically generated from property.h.j2.
// To regenerate, run `tools/propertygenerator/generate_properties.py`.

#pragma once

// clang-format off

#include <QDebug>


#include "../Color.h"
#include "ImagePropertyGroup.h"

#include "PropertiesTypes.h"

#include "union_export.h"

// clang-format on

namespace Union
{
namespace Properties
{

class BackgroundPropertyGroupPrivate;

/*!
\class Union::Properties::BackgroundPropertyGroup
\inmodule core
\ingroup core-properties

\brief A property group containing properties related to an element's background.

*/
class UNION_EXPORT BackgroundPropertyGroup
{
public:
    /*!
     * Default constructor. Constructs a null instance.
     *
     * A null instance in this case means an instance that does not have any
     * values for its properties. This includes property groups.
     */
    BackgroundPropertyGroup();
    /*!
     * Copy constructor.
     */
    BackgroundPropertyGroup(const BackgroundPropertyGroup &other);
    /*!
     * Move constructor.
     */
    BackgroundPropertyGroup(BackgroundPropertyGroup &&other);
    ~BackgroundPropertyGroup();

    /*!
     * Copy assignment operator.
     */
    BackgroundPropertyGroup &operator=(const BackgroundPropertyGroup &other);
    /*!
     * Move assignment operator.
     */
    BackgroundPropertyGroup &operator=(BackgroundPropertyGroup &&other);

    /*!
        The background color to use for an element.
     */
    std::optional<Union::Color> color() const;

    /*!
     * Set the value of color.
     *
     * \a newValue The new value or \c{std::nullopt} to unset the value.
     */
    void setColor(const std::optional<Union::Color> &newValue);

    /*!
     * The image to use for an element.
     */
    ImagePropertyGroup *image() const;

    /*!
     * Set the value of image.
     *
     * \a newValue The new value or \c{std::nullopt} to unset the value.
     */
    void setImage(std::unique_ptr<ImagePropertyGroup> &&newValue);

    /*!
     * Returns if this property group has any value set.
     *
     * Note that for any property that is also a property group, this will also
     * check if that group has any value.
     */
    bool hasAnyValue() const;

    /*!
     * Returns if this property is considered empty.
     *
     * A property is considered empty if it has no values or if the values it
     * contains are all considered empty values.
     */
    bool isEmpty() const;

    /*!
     * Returns a string representation of this property group.
     *
     * This is intended for debugging.
     *
     * \a indentation The amount of indentation to apply. Defaults to 0.
     * \a flags A set of flags that control conversion behavior.
     */
    QString toString(int indentation = 0, ToStringFlags flags = ToStringFlags{}) const;

    /*!
     * Copy property values from source to destination if destination does not have a property value.
     *
     * This will recursively copy property values of grouped properties.
     *
     * \a source      The source property group to copy from.
     * \a destination The destination property group to copy to.
     */
    static void resolveProperties(const BackgroundPropertyGroup *source, BackgroundPropertyGroup *destination);

    /*!
     * Create and return an empty BackgroundPropertyGroup instance.
     *
     * This will create an empty BackgroundPropertyGroup instance, which is defined as
     * an instance with all of its values default-constructed. Note that this is
     * different from a default-constructed instance which will have all its
     * values unset.
     */
    static std::unique_ptr<BackgroundPropertyGroup> empty();

private:
    std::unique_ptr<BackgroundPropertyGroupPrivate> d;
};

/*!
 * \relates Union::Properties::BackgroundPropertyGroup
 * Equality comparison for BackgroundPropertyGroup.
 */
UNION_EXPORT bool operator==(const BackgroundPropertyGroup &left, const BackgroundPropertyGroup &right);
}
}

/*!
 * \relates Union::Properties::BackgroundPropertyGroup
 * QDebug support for BackgroundPropertyGroup.
 */
UNION_EXPORT QDebug operator<<(QDebug debug, Union::Properties::BackgroundPropertyGroup *type);

UNION_EXPORT QDataStream &operator<<(QDataStream &stream, const Union::Properties::BackgroundPropertyGroup *type);
UNION_EXPORT QDataStream &operator>>(QDataStream &stream, std::unique_ptr<Union::Properties::BackgroundPropertyGroup> &type);