// SPDX-License-Identifier: LGPL-2.1-only OR LGPL-3.0-only OR LicenseRef-KDE-Accepted-LGPL
// SPDX-FileCopyrightText: 2024 Arjen Hiemstra <ahiemstra@heimr.nl>
//
// This file is automatically generated from property.h.j2.
// To regenerate, run `tools/propertygenerator/generate_properties.py`.

#pragma once

// clang-format off

#include <QDebug>



#include "PropertiesTypes.h"

#include "union_export.h"

// clang-format on

namespace Union
{
namespace Properties
{

class DisplayPropertyGroupPrivate;

/*!
\class Union::Properties::DisplayPropertyGroup
\inmodule core
\ingroup core-properties

\brief A property group containing properties related to how the element is displayed.

*/
class UNION_EXPORT DisplayPropertyGroup
{
public:
    /*!
     * Default constructor. Constructs a null instance.
     *
     * A null instance in this case means an instance that does not have any
     * values for its properties. This includes property groups.
     */
    DisplayPropertyGroup();
    /*!
     * Copy constructor.
     */
    DisplayPropertyGroup(const DisplayPropertyGroup &other);
    /*!
     * Move constructor.
     */
    DisplayPropertyGroup(DisplayPropertyGroup &&other);
    ~DisplayPropertyGroup();

    /*!
     * Copy assignment operator.
     */
    DisplayPropertyGroup &operator=(const DisplayPropertyGroup &other);
    /*!
     * Move assignment operator.
     */
    DisplayPropertyGroup &operator=(DisplayPropertyGroup &&other);

    /*!
        Whether the element should be shown or hidden.
     */
    std::optional<bool> visible() const;

    /*!
     * Set the value of visible.
     *
     * \a newValue The new value or \c{std::nullopt} to unset the value.
     */
    void setVisible(const std::optional<bool> &newValue);

    /*!
        The opacity of the element.
     */
    std::optional<qreal> opacity() const;

    /*!
     * Set the value of opacity.
     *
     * \a newValue The new value or \c{std::nullopt} to unset the value.
     */
    void setOpacity(const std::optional<qreal> &newValue);

    /*!
     * Returns if this property group has any value set.
     *
     * Note that for any property that is also a property group, this will also
     * check if that group has any value.
     */
    bool hasAnyValue() const;

    /*!
     * Returns if this property is considered empty.
     *
     * A property is considered empty if it has no values or if the values it
     * contains are all considered empty values.
     */
    bool isEmpty() const;

    /*!
     * Returns a string representation of this property group.
     *
     * This is intended for debugging.
     *
     * \a indentation The amount of indentation to apply. Defaults to 0.
     * \a flags A set of flags that control conversion behavior.
     */
    QString toString(int indentation = 0, ToStringFlags flags = ToStringFlags{}) const;

    /*!
     * Copy property values from source to destination if destination does not have a property value.
     *
     * This will recursively copy property values of grouped properties.
     *
     * \a source      The source property group to copy from.
     * \a destination The destination property group to copy to.
     */
    static void resolveProperties(const DisplayPropertyGroup *source, DisplayPropertyGroup *destination);

    /*!
     * Create and return an empty DisplayPropertyGroup instance.
     *
     * This will create an empty DisplayPropertyGroup instance, which is defined as
     * an instance with all of its values default-constructed. Note that this is
     * different from a default-constructed instance which will have all its
     * values unset.
     */
    static std::unique_ptr<DisplayPropertyGroup> empty();

private:
    std::unique_ptr<DisplayPropertyGroupPrivate> d;
};

/*!
 * \relates Union::Properties::DisplayPropertyGroup
 * Equality comparison for DisplayPropertyGroup.
 */
UNION_EXPORT bool operator==(const DisplayPropertyGroup &left, const DisplayPropertyGroup &right);
}
}

/*!
 * \relates Union::Properties::DisplayPropertyGroup
 * QDebug support for DisplayPropertyGroup.
 */
UNION_EXPORT QDebug operator<<(QDebug debug, Union::Properties::DisplayPropertyGroup *type);

UNION_EXPORT QDataStream &operator<<(QDataStream &stream, const Union::Properties::DisplayPropertyGroup *type);
UNION_EXPORT QDataStream &operator>>(QDataStream &stream, std::unique_ptr<Union::Properties::DisplayPropertyGroup> &type);