// SPDX-License-Identifier: LGPL-2.1-only OR LGPL-3.0-only OR LicenseRef-KDE-Accepted-LGPL
// SPDX-FileCopyrightText: 2024 Arjen Hiemstra <ahiemstra@heimr.nl>
//
// This file is automatically generated from property.h.j2.
// To regenerate, run `tools/propertygenerator/generate_properties.py`.

#pragma once

// clang-format off

#include <QDebug>


#include "AlignmentPropertyGroup.h"
#include "SizePropertyGroup.h"

#include "PropertiesTypes.h"

#include "union_export.h"

// clang-format on

namespace Union
{
namespace Properties
{

class LayoutPropertyGroupPrivate;

/*!
\class Union::Properties::LayoutPropertyGroup
\inmodule core
\ingroup core-properties

\brief A property group containing properties related to the layout of an element.
*/
class UNION_EXPORT LayoutPropertyGroup
{
public:
    /*!
     * Default constructor. Constructs a null instance.
     *
     * A null instance in this case means an instance that does not have any
     * values for its properties. This includes property groups.
     */
    LayoutPropertyGroup();
    /*!
     * Copy constructor.
     */
    LayoutPropertyGroup(const LayoutPropertyGroup &other);
    /*!
     * Move constructor.
     */
    LayoutPropertyGroup(LayoutPropertyGroup &&other);
    ~LayoutPropertyGroup();

    /*!
     * Copy assignment operator.
     */
    LayoutPropertyGroup &operator=(const LayoutPropertyGroup &other);
    /*!
     * Move assignment operator.
     */
    LayoutPropertyGroup &operator=(LayoutPropertyGroup &&other);

    /*!
     * Perform safe property lookup of a property or the property of a subgroup.
     *
     * This should be called with a list of property getter pointer-to-member
     * functions in \a functions that indicate which properties to access. Each
     * subgroup access will be checked to make sure the subgroup exists. If any
     * of them does not exist, \a defaultValue will be returned. The final
     * property lookup can be any member function of the final group. If that
     * returns a pointer or std::optional<>, it is checked to see if it has a
     * value. If it does, that value is returned. If not, \a defaultValue is
     * returned. For functions returning anything else, the value returned by
     * the function is returned.
     *
     * Example usage:
     *
     * \code
     * // Lookup the value of the property "spacing" of the "layout" group.
     * auto spacing = StylePropertyGroup->safePropertyLookup(0.0, &StylePropertyGroup::layout, &LayoutPropertyGroup::spacing);
     * \endcode
     */
    template<typename T, typename... LookupFunctions>
        requires(std::is_member_function_pointer_v<LookupFunctions> && ...)
    inline T safePropertyLookup(const T &defaultValue, LookupFunctions... functions) const
    {
        return Union::Properties::safePropertyLookup(this, defaultValue, functions...);
    }

    /*!
     * \brief A property group with properties related to alignment.
     */
    AlignmentPropertyGroup *alignment() const;

    /*!
     * Set the value of alignment.
     *
     * \a newValue The new value or \c{std::nullopt} to unset the value.
     */
    void setAlignment(std::unique_ptr<AlignmentPropertyGroup> &&newValue);

    /*!
        The implicit (initial) width of an element.
     */
    std::optional<qreal> width() const;

    /*!
     * Set the value of width.
     *
     * \a newValue The new value or \c{std::nullopt} to unset the value.
     */
    void setWidth(const std::optional<qreal> &newValue);

    /*!
        The implicit (initial) height of an element.
     */
    std::optional<qreal> height() const;

    /*!
     * Set the value of height.
     *
     * \a newValue The new value or \c{std::nullopt} to unset the value.
     */
    void setHeight(const std::optional<qreal> &newValue);

    /*!
        The spacing between various elements.
     */
    std::optional<qreal> spacing() const;

    /*!
     * Set the value of spacing.
     *
     * \a newValue The new value or \c{std::nullopt} to unset the value.
     */
    void setSpacing(const std::optional<qreal> &newValue);

    /*!
     * Padding defines extra spacing around the content of an element.
     */
    SizePropertyGroup *padding() const;

    /*!
     * Set the value of padding.
     *
     * \a newValue The new value or \c{std::nullopt} to unset the value.
     */
    void setPadding(std::unique_ptr<SizePropertyGroup> &&newValue);

    /*!
     * Inset defines extra spacing around the background of an element.
     */
    SizePropertyGroup *inset() const;

    /*!
     * Set the value of inset.
     *
     * \a newValue The new value or \c{std::nullopt} to unset the value.
     */
    void setInset(std::unique_ptr<SizePropertyGroup> &&newValue);

    /*!
     * Margins define extra spacing between sub-elements of an element.
     */
    SizePropertyGroup *margins() const;

    /*!
     * Set the value of margins.
     *
     * \a newValue The new value or \c{std::nullopt} to unset the value.
     */
    void setMargins(std::unique_ptr<SizePropertyGroup> &&newValue);

    /*!
     * Returns if this property group has any value set.
     *
     * Note that for any property that is also a property group, this will also
     * check if that group has any value.
     */
    bool hasAnyValue() const;

    /*!
     * Returns if this property is considered empty.
     *
     * A property is considered empty if it has no values or if the values it
     * contains are all considered empty values.
     */
    bool isEmpty() const;

    /*!
     * Returns a string representation of this property group.
     *
     * This is intended for debugging.
     *
     * \a indentation The amount of indentation to apply. Defaults to 0.
     * \a flags A set of flags that control conversion behavior.
     */
    QString toString(int indentation = 0, ToStringFlags flags = ToStringFlags{}) const;

    /*!
     * Copy property values from source to destination if destination does not have a property value.
     *
     * This will recursively copy property values of grouped properties.
     *
     * \a source      The source property group to copy from.
     * \a destination The destination property group to copy to.
     */
    static void resolveProperties(const LayoutPropertyGroup *source, LayoutPropertyGroup *destination);

    /*!
     * Create and return an empty LayoutPropertyGroup instance.
     *
     * This will create an empty LayoutPropertyGroup instance, which is defined as
     * an instance with all of its values default-constructed. Note that this is
     * different from a default-constructed instance which will have all its
     * values unset.
     */
    static std::unique_ptr<LayoutPropertyGroup> empty();

private:
    std::unique_ptr<LayoutPropertyGroupPrivate> d;
};

/*!
 * \relates Union::Properties::LayoutPropertyGroup
 * Equality comparison for LayoutPropertyGroup.
 */
UNION_EXPORT bool operator==(const LayoutPropertyGroup &left, const LayoutPropertyGroup &right);
}
}

/*!
 * \relates Union::Properties::LayoutPropertyGroup
 * QDebug support for LayoutPropertyGroup.
 */
UNION_EXPORT QDebug operator<<(QDebug debug, Union::Properties::LayoutPropertyGroup *type);

UNION_EXPORT QDataStream &operator<<(QDataStream &stream, const Union::Properties::LayoutPropertyGroup *type);
UNION_EXPORT QDataStream &operator>>(QDataStream &stream, std::unique_ptr<Union::Properties::LayoutPropertyGroup> &type);