// SPDX-License-Identifier: LGPL-2.1-only OR LGPL-3.0-only OR LicenseRef-KDE-Accepted-LGPL
// SPDX-FileCopyrightText: 2024 Arjen Hiemstra <ahiemstra@heimr.nl>
//
// This file is automatically generated from property.h.j2.
// To regenerate, run `tools/propertygenerator/generate_properties.py`.

#pragma once

// clang-format off

#include <QDebug>


#include "../Color.h"

#include "PropertiesTypes.h"

#include "union_export.h"

// clang-format on

namespace Union
{
namespace Properties
{

class LinePropertyGroupPrivate;

/*!
\class Union::Properties::LinePropertyGroup
\inmodule core
\ingroup core-properties

\brief A property group containing the properties of a line.
*/
class UNION_EXPORT LinePropertyGroup
{
public:
    /*!
     * Default constructor. Constructs a null instance.
     *
     * A null instance in this case means an instance that does not have any
     * values for its properties. This includes property groups.
     */
    LinePropertyGroup();
    /*!
     * Copy constructor.
     */
    LinePropertyGroup(const LinePropertyGroup &other);
    /*!
     * Move constructor.
     */
    LinePropertyGroup(LinePropertyGroup &&other);
    ~LinePropertyGroup();

    /*!
     * Copy assignment operator.
     */
    LinePropertyGroup &operator=(const LinePropertyGroup &other);
    /*!
     * Move assignment operator.
     */
    LinePropertyGroup &operator=(LinePropertyGroup &&other);

    /*!
        The thickness of the line.
     */
    std::optional<qreal> size() const;

    /*!
     * Set the value of size.
     *
     * \a newValue The new value or \c{std::nullopt} to unset the value.
     */
    void setSize(const std::optional<qreal> &newValue);

    /*!
        The color of the line.
     */
    std::optional<Union::Color> color() const;

    /*!
     * Set the value of color.
     *
     * \a newValue The new value or \c{std::nullopt} to unset the value.
     */
    void setColor(const std::optional<Union::Color> &newValue);

    /*!
        The style of the line.
     */
    std::optional<Union::Properties::LineStyle> style() const;

    /*!
     * Set the value of style.
     *
     * \a newValue The new value or \c{std::nullopt} to unset the value.
     */
    void setStyle(const std::optional<Union::Properties::LineStyle> &newValue);

    /*!
     * Returns if this property group has any value set.
     *
     * Note that for any property that is also a property group, this will also
     * check if that group has any value.
     */
    bool hasAnyValue() const;

    /*!
     * Returns if this property is considered empty.
     *
     * A property is considered empty if it has no values or if the values it
     * contains are all considered empty values.
     */
    bool isEmpty() const;

    /*!
     * Returns a string representation of this property group.
     *
     * This is intended for debugging.
     *
     * \a indentation The amount of indentation to apply. Defaults to 0.
     * \a flags A set of flags that control conversion behavior.
     */
    QString toString(int indentation = 0, ToStringFlags flags = ToStringFlags{}) const;

    /*!
     * Copy property values from source to destination if destination does not have a property value.
     *
     * This will recursively copy property values of grouped properties.
     *
     * \a source      The source property group to copy from.
     * \a destination The destination property group to copy to.
     */
    static void resolveProperties(const LinePropertyGroup *source, LinePropertyGroup *destination);

    /*!
     * Create and return an empty LinePropertyGroup instance.
     *
     * This will create an empty LinePropertyGroup instance, which is defined as
     * an instance with all of its values default-constructed. Note that this is
     * different from a default-constructed instance which will have all its
     * values unset.
     */
    static std::unique_ptr<LinePropertyGroup> empty();

private:
    std::unique_ptr<LinePropertyGroupPrivate> d;
};

/*!
 * \relates Union::Properties::LinePropertyGroup
 * Equality comparison for LinePropertyGroup.
 */
UNION_EXPORT bool operator==(const LinePropertyGroup &left, const LinePropertyGroup &right);
}
}

/*!
 * \relates Union::Properties::LinePropertyGroup
 * QDebug support for LinePropertyGroup.
 */
UNION_EXPORT QDebug operator<<(QDebug debug, Union::Properties::LinePropertyGroup *type);

UNION_EXPORT QDataStream &operator<<(QDataStream &stream, const Union::Properties::LinePropertyGroup *type);
UNION_EXPORT QDataStream &operator>>(QDataStream &stream, std::unique_ptr<Union::Properties::LinePropertyGroup> &type);