// SPDX-License-Identifier: LGPL-2.1-only OR LGPL-3.0-only OR LicenseRef-KDE-Accepted-LGPL
// SPDX-FileCopyrightText: 2024 Arjen Hiemstra <ahiemstra@heimr.nl>
//
// This file is automatically generated from property.cpp.j2.
// To regenerate, run `tools/propertygenerator/generate_properties.py`.

#include "LinePropertyGroup.h"

#include <QRegularExpression>

#include "PropertiesTypes.h"
#include "QDataStreamExtras.h"

using namespace Union::Properties;
using namespace Qt::StringLiterals;

class Union::Properties::LinePropertyGroupPrivate
{
public:
    std::optional<qreal> size;
    std::optional<Union::Color> color;
    std::optional<Union::Properties::LineStyle> style;
};

LinePropertyGroup::LinePropertyGroup()
    : d(std::make_unique<LinePropertyGroupPrivate>())
{
}

LinePropertyGroup::LinePropertyGroup(const LinePropertyGroup &other)
    : d(std::make_unique<LinePropertyGroupPrivate>())
{
    d->size = other.d->size;
    d->color = other.d->color;
    d->style = other.d->style;
}

LinePropertyGroup::LinePropertyGroup(LinePropertyGroup &&other)
    : d(std::move(other.d))
{
}

LinePropertyGroup::~LinePropertyGroup() = default;

LinePropertyGroup &LinePropertyGroup::operator=(const LinePropertyGroup &other)
{
    if (this != &other) {
        d->size = other.d->size;
        d->color = other.d->color;
        d->style = other.d->style;
    }
    return *this;
}

LinePropertyGroup &LinePropertyGroup::operator=(LinePropertyGroup &&other)
{
    std::swap(d, other.d);
    return *this;
}

std::optional<qreal> LinePropertyGroup::size() const
{
    return d->size;
}

void LinePropertyGroup::setSize(const std::optional<qreal> &newValue)
{
    if (newValue == d->size) {
        return;
    }

    d->size = newValue;
}

std::optional<Union::Color> LinePropertyGroup::color() const
{
    return d->color;
}

void LinePropertyGroup::setColor(const std::optional<Union::Color> &newValue)
{
    if (newValue == d->color) {
        return;
    }

    d->color = newValue;
}

std::optional<Union::Properties::LineStyle> LinePropertyGroup::style() const
{
    return d->style;
}

void LinePropertyGroup::setStyle(const std::optional<Union::Properties::LineStyle> &newValue)
{
    if (newValue == d->style) {
        return;
    }

    d->style = newValue;
}

bool LinePropertyGroup::hasAnyValue() const
{
    if (d->size.has_value()) {
        return true;
    }
    if (d->color.has_value()) {
        return true;
    }
    if (d->style.has_value()) {
        return true;
    }
    return false;
}

bool LinePropertyGroup::isEmpty() const
{
    if (!hasAnyValue()) {
        return true;
    }

    if (d->size.has_value() && d->size.value() != emptyValue<qreal>()) {
        return false;
    }
    if (d->color.has_value() && d->color.value() != emptyValue<Union::Color>()) {
        return false;
    }
    if (d->style.has_value() && d->style.value() != emptyValue<Union::Properties::LineStyle>()) {
        return false;
    }

    return true;
}

QString LinePropertyGroup::toString(int indentation, ToStringFlags flags) const
{
    if (!hasAnyValue()) {
        return u"(empty)"_s;
    }

    const bool multiline = flags & ToStringFlag::MultiLine;
    const bool types = flags & ToStringFlag::Types;

    QString result;
    QTextStream out(&result);

    constexpr auto indent = [](int amount, bool multiline, bool first) {
        if (multiline) {
            return QByteArray(amount, ' ');
        } else if (!first) {
            return QByteArray(", ");
        } else {
            return QByteArray(" ");
        }
    };

    const QByteArray maybeNewLine = multiline ? "\n" : "";
    const QByteArray empty = "(empty)";

    if (types) {
        out << "LinePropertyGroup(" << maybeNewLine;
    } else if (indentation > 0) {
        out << maybeNewLine;
    }

    out << indent(indentation, multiline, true) << "size: ";
    if (d->size) {
        out << d->size.value() << maybeNewLine;
    } else {
        out << empty << maybeNewLine;
    }
    out << indent(indentation, multiline, false) << "color: ";
    if (d->color) {
        out << d->color->toString() << maybeNewLine;
    } else {
        out << empty << maybeNewLine;
    }
    out << indent(indentation, multiline, false) << "style: ";
    if (d->style) {
        out << d->style.value() << maybeNewLine;
    } else {
        out << empty << maybeNewLine;
    }

    if (types) {
        out << indent(indentation - 2, multiline, true) << ")";
    }
    out << maybeNewLine;

    out.flush();

    return result;
}

void LinePropertyGroup::resolveProperties(const LinePropertyGroup *source, LinePropertyGroup *destination)
{
    if (!source || !destination) {
        return;
    }

    if (!destination->d->size.has_value()) {
        destination->d->size = source->d->size;
    }
    if (!destination->d->color.has_value()) {
        destination->d->color = source->d->color;
    }
    if (!destination->d->style.has_value()) {
        destination->d->style = source->d->style;
    }
}

std::unique_ptr<LinePropertyGroup> LinePropertyGroup::empty()
{
    auto result = std::make_unique<LinePropertyGroup>();
    result->d->size = emptyValue<qreal>();
    result->d->color = emptyValue<Union::Color>();
    result->d->style = emptyValue<Union::Properties::LineStyle>();
    return result;
}

bool Union::Properties::operator==(const LinePropertyGroup &left, const LinePropertyGroup &right)
{
    if (left.size() != right.size()) {
        return false;
    }
    if (left.color() != right.color()) {
        return false;
    }
    if (left.style() != right.style()) {
        return false;
    }
    return true;
}

QDebug operator<<(QDebug debug, Union::Properties::LinePropertyGroup *type)
{
    QDebugStateSaver saver(debug);
    debug.nospace() << qPrintable(type->toString(0, ToStringFlag::Types));
    return debug;
}

QDataStream &operator<<(QDataStream &stream, const Union::Properties::LinePropertyGroup *type)
{
    stream << type->size();
    stream << type->color();
    stream << type->style();
    return stream;
}

QDataStream &operator>>(QDataStream &stream, std::unique_ptr<Union::Properties::LinePropertyGroup> &type)
{
    {
        std::optional<qreal> data;
        stream >> data;
        type->setSize(data);
    }
    {
        std::optional<Union::Color> data;
        stream >> data;
        type->setColor(data);
    }
    {
        std::optional<Union::Properties::LineStyle> data;
        stream >> data;
        type->setStyle(data);
    }

    return stream;
}