// SPDX-License-Identifier: LGPL-2.1-only OR LGPL-3.0-only OR LicenseRef-KDE-Accepted-LGPL
//
// This file is automatically generated. To regenerate, run `generate_properties.py`.

#include "TextProperty.h"

using namespace Union::Properties;
using namespace Qt::StringLiterals;

class Union::Properties::TextPropertyPrivate
{
public:
    std::optional<Qt::Alignment> alignment;
    std::optional<QColor> color;
    std::optional<QFont> font;
};

TextProperty::TextProperty()
    : d(std::make_unique<TextPropertyPrivate>())
{
}

TextProperty::TextProperty(const TextProperty &other)
    : d(std::make_unique<TextPropertyPrivate>())
{
    d->alignment = other.d->alignment;
    d->color = other.d->color;
    d->font = other.d->font;
}

TextProperty::TextProperty(TextProperty &&other)
    : d(std::move(other.d))
{
}

TextProperty::~TextProperty() = default;

TextProperty &TextProperty::operator=(const TextProperty &other)
{
    if (this != &other) {
        d->alignment = other.d->alignment;
        d->color = other.d->color;
        d->font = other.d->font;
    }
    return *this;
}

TextProperty &TextProperty::operator=(TextProperty &&other)
{
    std::swap(d, other.d);
    return *this;
}

std::optional<Qt::Alignment> TextProperty::alignment() const
{
    return d->alignment;
}

void TextProperty::setAlignment(const std::optional<Qt::Alignment> &newValue)
{
    if (newValue == d->alignment) {
        return;
    }

    d->alignment = newValue;
}
std::optional<QColor> TextProperty::color() const
{
    return d->color;
}

void TextProperty::setColor(const std::optional<QColor> &newValue)
{
    if (newValue == d->color) {
        return;
    }

    d->color = newValue;
}
std::optional<QFont> TextProperty::font() const
{
    return d->font;
}

void TextProperty::setFont(const std::optional<QFont> &newValue)
{
    if (newValue == d->font) {
        return;
    }

    d->font = newValue;
}

bool TextProperty::hasAnyValue() const
{
    if (d->alignment.has_value()) {
        return true;
    }
    if (d->color.has_value()) {
        return true;
    }
    if (d->font.has_value()) {
        return true;
    }
    return false;
}

void TextProperty::resolveProperties(const TextProperty &source, TextProperty &destination)
{
    if (!destination.d->alignment.has_value()) {
        destination.d->alignment = source.d->alignment;
    }
    if (!destination.d->color.has_value()) {
        destination.d->color = source.d->color;
    }
    if (!destination.d->font.has_value()) {
        destination.d->font = source.d->font;
    }
}

bool Union::Properties::operator==(const TextProperty &left, const TextProperty &right)
{
    if (left.alignment() != right.alignment()) {
        return false;
    }
    if (left.color() != right.color()) {
        return false;
    }
    if (left.font() != right.font()) {
        return false;
    }
    return true;
}

QDebug operator<<(QDebug debug, const Union::Properties::TextProperty &type)
{
    QDebugStateSaver saver(debug);
    debug << "TextProperty(";
    debug << "  alignment:" << type.alignment();
    debug << "  color:" << type.color();
    debug << "  font:" << type.font();
    debug << ")";
    return debug;
}