// SPDX-License-Identifier: LGPL-2.1-only OR LGPL-3.0-only OR LicenseRef-KDE-Accepted-LGPL
// SPDX-FileCopyrightText: 2024 Arjen Hiemstra <ahiemstra@heimr.nl>
//
// This file is automatically generated from property.h.j2.
// To regenerate, run `tools/propertygenerator/generate_properties.py`.

#pragma once

// clang-format off

#include <QDebug>

#include <QFont>

#include "../Color.h"
#include "AlignmentPropertyGroup.h"

#include "PropertiesTypes.h"

#include "union_export.h"

// clang-format on

namespace Union
{
namespace Properties
{

class TextPropertyGroupPrivate;

/*!
\class Union::Properties::TextPropertyGroup
\inmodule core
\ingroup core-properties

\brief A property group containing properties related to the text of an element.

*/
class UNION_EXPORT TextPropertyGroup
{
public:
    /*!
     * Default constructor. Constructs a null instance.
     *
     * A null instance in this case means an instance that does not have any
     * values for its properties. This includes property groups.
     */
    TextPropertyGroup();
    /*!
     * Copy constructor.
     */
    TextPropertyGroup(const TextPropertyGroup &other);
    /*!
     * Move constructor.
     */
    TextPropertyGroup(TextPropertyGroup &&other);
    ~TextPropertyGroup();

    /*!
     * Copy assignment operator.
     */
    TextPropertyGroup &operator=(const TextPropertyGroup &other);
    /*!
     * Move assignment operator.
     */
    TextPropertyGroup &operator=(TextPropertyGroup &&other);

    /*!
     * Returns alignment if set or nullptr if not.
     */
    AlignmentPropertyGroup *alignment() const;

    /*!
     * Set the value of alignment.
     *
     * \a newValue The new value or \c{std::nullopt} to unset the value.
     */
    void setAlignment(std::unique_ptr<AlignmentPropertyGroup> &&newValue);

    /*!
     * Returns the value of font.
     */
    std::optional<QFont> font() const;

    /*!
     * Set the value of font.
     *
     * \a newValue The new value or \c{std::nullopt} to unset the value.
     */
    void setFont(const std::optional<QFont> &newValue);

    /*!
        The color of text of an element.
     */
    std::optional<Union::Color> color() const;

    /*!
     * Set the value of color.
     *
     * \a newValue The new value or \c{std::nullopt} to unset the value.
     */
    void setColor(const std::optional<Union::Color> &newValue);

    /*!
        The wrap mode for the text of an element.
     */
    std::optional<Union::Properties::TextWrapMode> wrapMode() const;

    /*!
     * Set the value of wrapMode.
     *
     * \a newValue The new value or \c{std::nullopt} to unset the value.
     */
    void setWrapMode(const std::optional<Union::Properties::TextWrapMode> &newValue);

    /*!
        The elide mode for the text of an element.
     */
    std::optional<Union::Properties::TextElide> elide() const;

    /*!
     * Set the value of elide.
     *
     * \a newValue The new value or \c{std::nullopt} to unset the value.
     */
    void setElide(const std::optional<Union::Properties::TextElide> &newValue);

    /*!
     * Returns if this property group has any value set.
     *
     * Note that for any property that is also a property group, this will also
     * check if that group has any value.
     */
    bool hasAnyValue() const;

    /*!
     * Returns if this property is considered empty.
     *
     * A property is considered empty if it has no values or if the values it
     * contains are all considered empty values.
     */
    bool isEmpty() const;

    /*!
     * Returns a string representation of this property group.
     *
     * This is intended for debugging.
     *
     * \a indentation The amount of indentation to apply. Defaults to 0.
     * \a flags A set of flags that control conversion behavior.
     */
    QString toString(int indentation = 0, ToStringFlags flags = ToStringFlags{}) const;

    /*!
     * Copy property values from source to destination if destination does not have a property value.
     *
     * This will recursively copy property values of grouped properties.
     *
     * \a source      The source property group to copy from.
     * \a destination The destination property group to copy to.
     */
    static void resolveProperties(const TextPropertyGroup *source, TextPropertyGroup *destination);

    /*!
     * Create and return an empty TextPropertyGroup instance.
     *
     * This will create an empty TextPropertyGroup instance, which is defined as
     * an instance with all of its values default-constructed. Note that this is
     * different from a default-constructed instance which will have all its
     * values unset.
     */
    static std::unique_ptr<TextPropertyGroup> empty();

private:
    std::unique_ptr<TextPropertyGroupPrivate> d;
};

/*!
 * \relates Union::Properties::TextPropertyGroup
 * Equality comparison for TextPropertyGroup.
 */
UNION_EXPORT bool operator==(const TextPropertyGroup &left, const TextPropertyGroup &right);
}
}

/*!
 * \relates Union::Properties::TextPropertyGroup
 * QDebug support for TextPropertyGroup.
 */
UNION_EXPORT QDebug operator<<(QDebug debug, Union::Properties::TextPropertyGroup *type);

UNION_EXPORT QDataStream &operator<<(QDataStream &stream, const Union::Properties::TextPropertyGroup *type);
UNION_EXPORT QDataStream &operator>>(QDataStream &stream, std::unique_ptr<Union::Properties::TextPropertyGroup> &type);